name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_DUNE_0A317DA03 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "Legal" # App source code path
          api_location: "Legal/api" # Api source code path - optional
          skip_app_build: "true"
          skip_api_build: "true"
          ###### End of Repository/Build Configurations ######

      - name: Warmup Function (optional)
        env:
          SWA_WARMUP_URL: ${{ secrets.SWA_WARMUP_URL }}
        continue-on-error: true
        run: |
          if [ -z "$SWA_WARMUP_URL" ]; then
            echo "No SWA_WARMUP_URL secret set; skipping warmup."; exit 0
          fi
          echo "Warming up $SWA_WARMUP_URL"
          for i in 1 2 3; do
            if curl -sS --max-time 15 "$SWA_WARMUP_URL"; then
              echo "Warmup successful"; exit 0
            fi
            echo "Warmup try $i failed; sleeping 5s"; sleep 5
          done
          echo "Warmup failed (non-blocking)."

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_DUNE_0A317DA03 }}
          action: "close"
          app_location: "Legal"
